### ISSUE TITLE
Gass lamp not work after 0.3 release

### ISSUE THREAD

**Issue by mo1seev** [sbidy/wiz_light#103]
{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb50bfe790","homeId":1756465,"roomId":2614452,"moduleName":"ESP56_SHTW3_01","fwVersion":"1.21.2","groupId":0,"drvConf":[20,1],"ewf":[255,0,223,255,0,0,38],"ewfHex":"ff00dfff000026","ping":0}}

2021-02-07 11:46:13 ERROR (MainThread) [homeassistant.components.light] wiz_light: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/config/custom_components/wiz_light/light.py", line 246, in async_update
    await self.get_bulb_type()
  File "/config/custom_components/wiz_light/light.py", line 367, in get_bulb_type
    self._bulbtype = await self._light.get_bulbtype()
  File "/usr/local/lib/python3.8/site-packages/pywizlight/bulb.py", line 255, in get_bulbtype
    raise WizLightNotKnownBulb("The bulb is unknown to the intergration.")
pywizlight.exceptions.WizLightNotKnownBulb: The bulb is unknown to the intergration.

**Comment by mo1seev** [comment]
And same with other gauss model

echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 192.168.1.54 38899
{"method":"getSystemConfig","env":"pro","result":{"mac":"a8bb50c66c8b","homeId":1756465,"roomId":3756326,"moduleName":"ESP12_SHTW1_01W","fwVersion":"1.21.2","groupId":0,"drvConf":[20,1],"ewf":[255,0,255,255,0,0,0],"ewfHex":"ff00ffff000000","ping":0}}

**Comment by sbidy** [comment]
I'm currently update the backend lib with an auto mapping. Please stay tuned. The 0.3.2 will resolve (hopefully and finally) this annoying issue.

**Comment by sbidy** [comment]
Can you please test with the new 0.4. ? This should fix the issue.

**Comment by mo1seev** [comment]
Not  working.

2021-02-12 09:45:50 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform wiz_light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 421, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 462, in capability_attributes
    data[ATTR_EFFECT_LIST] = self.effect_list
  File "/config/custom_components/wiz_light/light.py", line 224, in effect_list
    return [
  File "/config/custom_components/wiz_light/light.py", line 225, in <listcomp>
    self._scenes[key]
IndexError: list index out of range

**Comment by sbidy** [comment]
Ok - from on error to another 😞.
I'll check that - it seems to be an error with effect "detection". For the TW (tunable white) bulbs.

**Comment by excalbian** [comment]
> Not working.


> IndexError: list index out of range

If this is the same as the similar error I faced in #118, I can confirm that after upgrading to current `master` the TW bulbs are working.

**Comment by sbidy** [comment]
Ok, cool. Thank you for the feedback.

**Comment by mo1seev** [comment]
I pull master branch and it still not working. When i try add lamp from GUI i have this error:

```
2021-02-28 23:21:37 ERROR (MainThread) [homeassistant.components.light] Error while setting up wiz_light platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 206, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 421, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 462, in capability_attributes
    data[ATTR_EFFECT_LIST] = self.effect_list
  File "/config/custom_components/wiz_light/light.py", line 224, in effect_list
    return [
  File "/config/custom_components/wiz_light/light.py", line 225, in <listcomp>
    self._scenes[key]
IndexError: list index out of range
```

**Comment by mo1seev** [comment]
Hey sbidy. I tried again pull master branch and its work! Thanks for your hard work!
