### ISSUE TITLE
Errors during start up

### ISSUE THREAD

**Issue by Rjaap** [sbidy/wiz_light#121]
Sometimes during a restart of home assistant there is an error while setting up the Wiz component i. Consequently the Wiz lights become unresponsive:

`021-02-25`` 09:57:50 ERROR (MainThread) [homeassistant.components.light] Error while setting up wiz_light platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 206, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 421, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 462, in capability_attributes
    data[ATTR_EFFECT_LIST] = self.effect_list
  File "/config/custom_components/wiz_light/light.py", line 224, in effect_list
    return [
  File "/config/custom_components/wiz_light/light.py", line 225, in <listcomp>
    self._scenes[key]
IndexError: list index out of range'

I'm using version 0.4 of the component. When I reinstall the component the error goes away, just to reappear again in a couple of days. Funning thing is, it doesn't happen at every restart, just every few days or so.

**Comment by sbidy** [comment]
There are an issue with the effect list mapping in some special cases.
The current branch should fix the issue. You can test with a git-clone. A release is currently not available from these branch.

**Comment by Rjaap** [comment]
Thanks! I installed the master version via HACS. Until now no problems

**Comment by Rjaap** [comment]
Haven't seen the error again, so I'm closing this one.
