### ISSUE TITLE
Lost advanced light bulb functionality with HA 2021.6.6 Update

### ISSUE THREAD

**Issue by riccidan** [sbidy/wiz_light#153]
Hi there,

I seem to have lost the light integration from my Wiz light since having updated to 2021.6.6.

It's still possible to switch on and off as it appears as an automation, but no longer as a light.
![Screenshot 2021-06-27 084644](https://user-images.githubusercontent.com/69840406/123527597-461c8200-d724-11eb-97af-8e4d8db08eeb.png)

Do I need to reinstall the custom integration?

By the way, really appreciate all the work you have invested in this integration, to date has worked fantastically.

**Comment by sbidy** [comment]
I'm not aware of an major change in the HASS API which breaks the integration.
It can be possible that you have to re-install the integration and re-add the lights via ConfigFlow (add the bulbs via UI not via YAML). 

Do you have a log or an error message?

**Comment by zachberger** [comment]
I'm seeing this too. Here are my logs after upgrade

```
2021-07-15 16:26:16 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration qbittorrent_alternative_speed which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-15 16:26:16 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-15 16:26:16 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration wiz_light which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-15 16:26:16 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-15 16:26:16 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration circadian_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-15 16:26:16 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-15 16:26:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139654400668576] Received invalid command: mobile_app/push_notification_channel
2021-07-15 16:26:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139654400668576] Received invalid command: mobile_app/push_notification_channel
2021-07-15 16:27:01 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139654400668576] Received invalid command: mobile_app/push_notification_channel
2021-07-15 16:27:13 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook b72a8cd7588f7ccc91e34b42b98dd0720638349b6c0f161d39b2afb6149c83a5 from 10.1.1.137
2021-07-15 16:27:13 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook b72a8cd7588f7ccc91e34b42b98dd0720638349b6c0f161d39b2afb6149c83a5 from 10.1.1.137
2021-07-15 16:27:16 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook b72a8cd7588f7ccc91e34b42b98dd0720638349b6c0f161d39b2afb6149c83a5 from 10.1.1.137
2021-07-15 16:27:16 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook b72a8cd7588f7ccc91e34b42b98dd0720638349b6c0f161d39b2afb6149c83a5 from 10.1.1.137
2021-07-15 16:27:24 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: airvisual, hacs, media_player.yamaha
2021-07-15 16:27:28 ERROR (MainThread) [homeassistant.components.light] wiz_light: Error on device update!
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 481, in sendUDPMessage
stream = await asyncio.wait_for(
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
return fut.result()
File "/usr/local/lib/python3.9/site-packages/asyncio_dgram/aio.py", line 247, in connect
transport, protocol = await loop.create_datagram_endpoint(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1296, in create_datagram_endpoint
infos = await self._ensure_resolved(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
return await loop.getaddrinfo(host, port, family=family, type=type,
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
return await self.run_in_executor(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 520, in sendUDPMessage
stream.close()
UnboundLocalError: local variable 'stream' referenced before assignment
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 601, in async_device_update
await task
File "/config/custom_components/wiz_light/light.py", line 251, in async_update
await self.update_state()
File "/config/custom_components/wiz_light/light.py", line 290, in update_state
await self._light.updateState()
File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 424, in updateState
resp = await self.sendUDPMessage(message)
File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 522, in sendUDPMessage
raise WizLightConnectionError(
pywizlight.exceptions.WizLightConnectionError: Bulb is offline or IP address is not correct.
2021-07-15 16:27:31 WARNING (Recorder) [homeassistant.components.recorder.migration] Database is about to upgrade. Schema version: 16
```

I suspect the one error is due to one of my lights actually being offline

**Comment by zachberger** [comment]
Also, my bulbs were initially installed via ConfigFlow. I really hope I won't have to re-add them. I have ~50 lights
